### ISSUE TITLE
Issue with mobile app since latest update

### ISSUE THREAD

**Issue by arboeh** [AmoebeLabs/flex-horseshoe-card#53] opened 2022-06-13 07:13 UTC
I have a problem since the mobile app update to 2022.6.0. It's working fine with browser version and worked in mobile app before.
Pushing the now "invisible" fan button in mobile app gives me the following error:

```
Logger: frontend.js.latest.202206010
Source: components/system_log/__init__.py:190
First occurred: 08:54:06 (1 occurrences)
Last logged: 08:54:06

https://xxxxxxxxxxx.duckdns.org:8123/hacsfiles/flex-horseshoe-card/flex-horseshoe-card.js?hacstag=1111111111:222:333 Uncaught TypeError: Cannot read properties of undefined (reading 'action')
```

Mobile app:
![mobile](https://user-images.githubusercontent.com/12322114/173299260-9c0b6b76-ee85-46d5-8501-7b11c2405a82.jpg)

Browser:
![browser](https://user-images.githubusercontent.com/12322114/173298912-8a3a43ca-eed4-4ddb-bc6f-0b5a687ec4ba.png)

Lovelace-Configuration:
```
type: custom:mod-card
card_mod:
  style: |
    restriction-card {
      --lock-margin-left: 88%;
    }
card:
  type: custom:restriction-card
  restrictions:
    block: true
  condition:
    entity: sensor.i3s_120_remaining_battery_percent
    value: 30
    operator: <
  card:
    type: custom:flex-horseshoe-card
    entities:
      - entity: sensor.i3s_location_temp
        decimals: 1
        name: ' '
        tap_action:
          action: more-info
      - entity: input_boolean.virtual_i3s_climate
        icon: mdi:fan
        tap_action:
          action: call-service
          service: input_boolean.toggle
          service_data:
            entity_id: input_boolean.virtual_i3s_climate
      - entity: switch.virtual_i3s_climate
      - entity: sensor.i3s_loc
        tap_action:
          action: more-info
    animations:
      entity.1:
        - state: 'on'
          icons:
            - animation_id: 0
              styles:
                - color: var(--paper-item-icon-active-color);
        - state: 'off'
          icons:
            - animation_id: 0
              styles:
                - color: var(--primary-text-color);
      entity.2:
        - state: 'on'
          icons:
            - animation_id: 0
              styles:
                - color: var(--text-primary-color);
          circles:
            - animation_id: 1
              styles:
                - fill: var(--cool-blue);
        - state: 'off'
          circles:
            - animation_id: 1
              styles:
                - fill: var(--primary-background-color);
    show:
      horseshoe_style: colorstopgradient
    layout:
      states:
        - id: 0
          entity_index: 0
          xpos: 50
          ypos: 42
          styles:
            - font-size: 3.5em;
            - text-transform: none;
            - font-weight: 500;
        - id: 1
          entity_index: 3
          xpos: 50
          ypos: 95
          styles:
            - text-transform: lowercase;
            - font-size: 1.6em;
            - font-weight: 500;
            - letter-spacing: inherit;
      hlines:
        - id: 0
          xpos: 50
          ypos: 51
          length: 50
          styles:
            - stroke: var(--primary-text-color);
            - stroke-width: 5;
            - stroke-linecap: round;
            - opacity: 0.7;
      names:
        - id: 0
          entity_index: 0
          xpos: 50
          ypos: 95
          styles:
            - text-transform: lowercase;
            - font-size: 1.6em;
            - font-weight: 500;
            - letter-spacing: inherit;
      icons:
        - id: 0
          entity_index: 1
          animation_id: 0
          xpos: 50
          ypos: 74
          icon_size: 3.8
      circles:
        - id: 0
          entity_index: 2
          animation_id: 1
          xpos: 50
          ypos: 68.5
          radius: 25
    horseshoe_scale:
      min: -20
      max: 60
      width: 10
    horseshoe_state:
      width: 14
    color_stops:
      '10': orange
      '18': var(--cool-blue)
      '25': orange
      '35': red
      '-20': red
    card_mod:
      style: |
        ha-card {
          padding: 12px !important;
        }
```

**Comment by isorin** [comment] 2022-06-24 14:28
Same here, but I don't think we'll get any updates. The development on this repo seems to have stopped.
I submitted a fix for another issue some time ago but no replies.

![screenshot](https://user-images.githubusercontent.com/17415569/175556631-b5c8296c-931f-4d39-8e27-5570128191fa.png)

**Comment by ametodi** [comment] 2023-01-09 15:16
A fix for this would be very much appreciated!!

**Comment by AmoebeLabs** [comment] 2023-05-01 15:46
As this is caused by a change in the mobile app 2202.6, I think this one is related to (#48), as I see very small icons in the last Mobile screenshot, next to the temperature!

- #48 will be fixed in the next release!

**Closed as completed** 2023-05-02 09:46 UTC
Labels: bug, os/android

**Comment by SzymaneKwr** [comment] 2023-05-16 10:38
I'm still having trouble displaying icons on android. Will it be repaired? I have version 1.2 horseshoe

**Comment by AmoebeLabs** [comment] 2023-05-16 11:24
> I'm still having trouble displaying icons on android. Will it be repaired? I have version 1.2 horseshoe

Did you clear the Companion Apps frontend cache?

Can you give my some screenshots, and the Android / Webview version you are using?

If you use Chrome on your Android device, are the icons then displayed correctly?

**Comment by SzymaneKwr** [comment] 2023-05-16 11:39
> > I'm still having trouble displaying icons on android. Will it be repaired? I have version 1.2 horseshoe
> 
> Did you clear the Companion Apps frontend cache?
> 
> Can you give my some screenshots, and the Android / Webview version you are using?
> 
> If you use Chrome on your Android device, are the icons then displayed correctly?

I'm very sorry. I cleared the data of the companion app and everything is ok.

**Comment by AmoebeLabs** [comment] 2023-05-16 12:46
> I'm very sorry. I cleared the data of the companion app and everything is ok.

No problem. I’m used to clear the frontend cache with every software update I make, for others it is something one does almost never.

At least I now know the fix works!
